"""
diseases.py — MedReport AI v7.0
55 diseases across 10 body system categories.
Every entry guaranteed to produce output for any input.
"""

ALL_CATEGORIES = {
    "🫁 Lungs & Breathing":    "#2563eb",
    "❤️ Heart & Blood":        "#dc2626",
    "🧠 Brain & Nerves":       "#7c3aed",
    "🍽️ Stomach & Digestion":  "#d97706",
    "🩸 Diabetes & Hormones":  "#db2777",
    "🦴 Bones & Joints":       "#0891b2",
    "🫘 Kidneys & Urology":    "#059669",
    "🧠 Mental Health":        "#6d28d9",
    "🦠 Infections":           "#ea580c",
    "👁️ Skin & Eyes":          "#0f766e",
}

DISEASE_DB = {

    # ══════════════════════════════════════════════════════
    # LUNGS & BREATHING
    # ══════════════════════════════════════════════════════
    "Chronic Obstructive Pulmonary Disease (COPD)": {
        "plain":"Lung Breathing Problem (COPD)", "icon":"🫁", "color":"#2563eb",
        "category":"🫁 Lungs & Breathing", "icd10":"J44.1", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 2–4 weeks",
        "what":"COPD means the lungs are damaged — usually from years of smoking — making it hard to breathe. Air gets trapped causing constant coughing, wheezing and breathlessness.",
        "aliases":["copd","chronic obstructive pulmonary disease","emphysema","chronic bronchitis"],
        "kws":["cough","smoking","wheeze","dyspnea","breathlessness","sputum","fev1","spirometry","barrel chest","hyperinflation","emphysema","bronchitis","copd","exacerbation","obstructive"],
        "boost":["cough","wheeze","dyspnea","breathlessness","sputum","fev1","copd"],
        "symptoms":["Persistent cough that won't stop","Wheezing or whistling when breathing","Feeling breathless even during light activity","Producing thick mucus every day"],
        "meds":[("Tiotropium inhaler","Once-daily inhaler that keeps airways open all day"),("Albuterol inhaler","Quick-relief inhaler — use when suddenly short of breath"),("Fluticasone inhaler","Reduces swelling inside airways"),("Ipratropium","Relaxes the muscles around airways")],
        "specs":[("Lung Doctor (Pulmonologist)","Treats all breathing and lung conditions"),("Respiratory Therapist","Teaches correct breathing and inhaler technique")],
        "tips":["Stop smoking — the single most important step","Gentle breathing exercises every day","Get flu vaccine every year","Avoid dusty and smoky environments"],
    },
    "Asthma": {
        "plain":"Asthma (Airway Tightening)", "icon":"💨", "color":"#3b82f6",
        "category":"🫁 Lungs & Breathing", "icd10":"J45.909", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 1–2 weeks",
        "what":"In asthma, the airways get inflamed and narrow down making it hard to breathe. Attacks can be triggered by dust, pollen, cold air, exercise or stress.",
        "aliases":["asthma","bronchial asthma","reactive airway","bronchospasm"],
        "kws":["asthma","wheeze","breathlessness","chest tightness","inhaler","bronchospasm","pollen","dust","allergy","peak flow","bronchodilator","atopic","rescue inhaler"],
        "boost":["asthma","wheeze","chest tightness","bronchospasm"],
        "symptoms":["Sudden attacks of breathlessness","Wheezing when breathing out","Tight feeling in the chest","Cough worse at night or early morning"],
        "meds":[("Salbutamol (blue rescue inhaler)","Use immediately during an attack"),("Beclometasone (brown preventer)","Take every day to stop attacks"),("Montelukast","Daily tablet reducing airway inflammation"),("Prednisolone","Short steroid course for severe attacks")],
        "specs":[("Lung Doctor (Pulmonologist)","Specialist for asthma management"),("Allergy Specialist","Identifies and treats allergens triggering asthma")],
        "tips":["Always carry your blue rescue inhaler","Avoid known triggers like dust, smoke, pets","Use preventer inhaler every day even when well","Check your peak flow meter regularly"],
    },
    "Pneumonia": {
        "plain":"Lung Infection (Pneumonia)", "icon":"🌡️", "color":"#ea580c",
        "category":"🫁 Lungs & Breathing", "icd10":"J18.9", "urgency_level":"high",
        "urgency":"🚨 See a doctor immediately",
        "what":"A bacterial or viral infection inflames the air sacs in one or both lungs. The sacs fill with fluid making it very hard to breathe.",
        "aliases":["pneumonia","community acquired pneumonia","cap","lung infection","lobar pneumonia"],
        "kws":["pneumonia","fever","cough","consolidation","infiltrate","crackles","lobar","sputum","chest pain","pleuritic","rigors","tachypnea","opacity"],
        "boost":["pneumonia","fever","consolidation","crackles","infiltrate"],
        "symptoms":["High fever with shaking chills","Cough with thick yellow or green mucus","Sharp chest pain when breathing deeply","Feeling very breathless and weak"],
        "meds":[("Amoxicillin","Common antibiotic killing the bacteria"),("Azithromycin","5-day antibiotic for many lung infections"),("Levofloxacin","Stronger antibiotic for stubborn infections"),("Ceftriaxone","Hospital injection antibiotic for severe cases")],
        "specs":[("Lung Doctor (Pulmonologist)","Manages lung infections"),("Infectious Disease Specialist","Treats complex or severe infections")],
        "tips":["Rest completely and drink lots of water","Complete your full antibiotic course — never stop early","Get pneumonia vaccine","Go to hospital immediately if breathing becomes very difficult"],
    },
    "Pulmonary Tuberculosis": {
        "plain":"Lung TB (Tuberculosis)", "icon":"🦠", "color":"#b45309",
        "category":"🫁 Lungs & Breathing", "icd10":"A15.0", "urgency_level":"high",
        "urgency":"🚨 See a doctor immediately — TB is contagious",
        "what":"TB is a bacterial infection that mainly attacks the lungs. It spreads through the air when an infected person coughs. Treatable but requires at least 6 months of antibiotics.",
        "aliases":["tuberculosis","tb","pulmonary tb","mycobacterium tuberculosis","koch"],
        "kws":["tuberculosis","tb","haemoptysis","night sweats","weight loss","cough","sputum","afb","mantoux","cavitation","apical","mycobacterium","rifampicin","isoniazid"],
        "boost":["tuberculosis","tb","haemoptysis","night sweats","cavitation","afb"],
        "symptoms":["Cough lasting more than 3 weeks","Coughing up blood","Soaking night sweats","Unexplained weight loss and fatigue"],
        "meds":[("Isoniazid","Core TB antibiotic taken for 6 months"),("Rifampicin","Key TB drug — turns urine orange, which is normal"),("Pyrazinamide","TB antibiotic used in the first 2 months"),("Ethambutol","Fourth TB drug used in initial phase")],
        "specs":[("Lung Doctor (Pulmonologist)","Manages TB treatment"),("Infectious Disease Specialist","Specialist for complex TB cases")],
        "tips":["Take all TB medicines every single day","Wear a mask around others until non-infectious","Ensure good ventilation at home","Inform close contacts to get tested"],
    },
    "Sleep Apnea": {
        "plain":"Sleep Breathing Stops (Sleep Apnea)", "icon":"😴", "color":"#4f46e5",
        "category":"🫁 Lungs & Breathing", "icd10":"G47.33", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4 weeks",
        "what":"During sleep the throat muscles relax and block the airway, causing breathing to stop repeatedly. This disrupts sleep and reduces oxygen to the brain and heart.",
        "aliases":["sleep apnea","sleep apnoea","obstructive sleep apnea","osa","snoring disorder"],
        "kws":["sleep apnea","apnoea","snoring","apnea","hypopnea","ahi","cpap","oxygen desaturation","daytime sleepiness","fatigue","somnolence"],
        "boost":["sleep apnea","snoring","ahi","cpap"],
        "symptoms":["Very loud snoring at night","Waking up gasping for air","Extreme tiredness during the day","Waking with morning headaches"],
        "meds":[("CPAP machine","Air pressure device worn at night — keeps airway open"),("Weight loss programme","Losing weight significantly reduces sleep apnea"),("Positional therapy","Sleeping on your side reduces blockages")],
        "specs":[("Sleep Specialist","Diagnoses and treats sleep disorders"),("ENT Doctor","Checks for physical causes of airway blockage")],
        "tips":["Sleep on your side not your back","Lose weight if overweight","Avoid alcohol and sleeping tablets","Use CPAP machine every night without fail"],
    },

    # ══════════════════════════════════════════════════════
    # HEART & BLOOD
    # ══════════════════════════════════════════════════════
    "Hypertension": {
        "plain":"High Blood Pressure", "icon":"❤️", "color":"#dc2626",
        "category":"❤️ Heart & Blood", "icd10":"I10", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 1 month",
        "what":"The heart pumps blood with too much force. Over time this silently damages the heart, kidneys and brain — called the silent killer because there are usually no symptoms.",
        "aliases":["hypertension","high blood pressure","htn","elevated bp"],
        "kws":["blood pressure","hypertension","systolic","diastolic","mmhg","amlodipine","lisinopril","antihypertensive","lvh","htn","bp elevated","elevated bp"],
        "boost":["blood pressure","hypertension","systolic","htn"],
        "symptoms":["Usually no symptoms at all","Occasional headaches","Feeling dizzy or lightheaded","Blurred vision in severe cases"],
        "meds":[("Amlodipine","Relaxes blood vessels so heart doesn't work so hard"),("Lisinopril","Protects blood vessels and kidneys"),("Hydrochlorothiazide","Water tablet — removes extra fluid to lower pressure"),("Losartan","Blocks chemicals that tighten blood vessels")],
        "specs":[("Heart Doctor (Cardiologist)","Specialist for heart and blood vessel problems"),("General Physician","Family doctor can manage blood pressure well")],
        "tips":["Reduce salt in your food","Exercise daily — even regular walking helps","Avoid smoking and limit alcohol","Manage stress with relaxation techniques"],
    },
    "Heart Attack (Myocardial Infarction)": {
        "plain":"Heart Attack", "icon":"💔", "color":"#b91c1c",
        "category":"❤️ Heart & Blood", "icd10":"I21.9", "urgency_level":"critical",
        "urgency":"🚨 CALL EMERGENCY SERVICES IMMEDIATELY",
        "what":"A heart attack happens when blood flow to part of the heart is completely blocked. Heart muscle starts to die without blood. Every minute matters — call emergency services immediately.",
        "aliases":["heart attack","myocardial infarction","mi","stemi","nstemi","cardiac arrest","acs"],
        "kws":["chest pain","myocardial infarction","heart attack","troponin","ecg","stemi","nstemi","angina","left arm pain","jaw pain","diaphoresis","crushing chest","cardiac","ischemia","infarction"],
        "boost":["chest pain","myocardial infarction","troponin","stemi","heart attack","infarction"],
        "symptoms":["Crushing or squeezing chest pain","Pain spreading to left arm, jaw or back","Profuse sweating for no reason","Nausea, dizziness and breathlessness"],
        "meds":[("Aspirin 300mg","Chew immediately if heart attack suspected"),("Nitroglycerin spray","Spray under tongue to widen arteries"),("Heparin injection","Blood thinner given in hospital"),("Atorvastatin","Prevents future heart attacks")],
        "specs":[("Heart Doctor (Cardiologist)","Emergency heart specialist"),("Interventional Cardiologist","Performs emergency stent procedures")],
        "tips":["Call emergency services first — do not drive yourself","Chew an aspirin while waiting for ambulance","Do not eat or drink anything","Complete cardiac rehab after recovery"],
    },
    "Heart Failure": {
        "plain":"Weak Heart (Heart Failure)", "icon":"🫀", "color":"#e11d48",
        "category":"❤️ Heart & Blood", "icd10":"I50.9", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 1 week",
        "what":"Heart failure means the heart is too weak to pump blood efficiently. Fluid builds up in the legs and lungs causing swelling and breathlessness.",
        "aliases":["heart failure","congestive heart failure","chf","cardiac failure","decompensated heart failure"],
        "kws":["heart failure","dyspnea","orthopnea","pnd","edema","oedema","ejection fraction","bnp","jvp","cardiomegaly","pulmonary edema","chf","fluid overload"],
        "boost":["heart failure","dyspnea","oedema","ejection fraction","bnp","orthopnea"],
        "symptoms":["Swollen ankles and legs","Breathlessness when lying flat","Waking at night gasping for air","Extreme tiredness with little effort"],
        "meds":[("Furosemide","Water tablet — removes extra fluid causing swelling"),("Ramipril","Protects heart and reduces its workload"),("Bisoprolol","Slows the heart so it pumps more efficiently"),("Spironolactone","Removes extra fluid and protects heart muscle")],
        "specs":[("Heart Doctor (Cardiologist)","Manages heart failure treatment"),("Heart Failure Nurse","Specialist nurse monitoring treatment")],
        "tips":["Weigh yourself every morning — sudden weight gain means fluid buildup","Limit fluid intake as advised","Reduce salt in all food","Light daily exercise as advised by your doctor"],
    },
    "Atrial Fibrillation": {
        "plain":"Irregular Heartbeat (AF)", "icon":"📉", "color":"#f43f5e",
        "category":"❤️ Heart & Blood", "icd10":"I48.91", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 1 week",
        "what":"The upper chambers of the heart beat chaotically instead of in a regular rhythm. This increases risk of blood clots forming and causing a stroke.",
        "aliases":["atrial fibrillation","af","afib","arrhythmia","irregular heartbeat","cardiac arrhythmia","flutter"],
        "kws":["atrial fibrillation","af","afib","palpitations","arrhythmia","irregular heartbeat","anticoagulant","warfarin","flutter","cardioversion","irregular pulse"],
        "boost":["atrial fibrillation","afib","palpitations","arrhythmia"],
        "symptoms":["Heart fluttering or racing feeling in chest","Feeling breathless for no reason","Feeling dizzy or faint","Extreme tiredness"],
        "meds":[("Warfarin / Apixaban","Blood thinner to prevent stroke from clots"),("Bisoprolol","Slows the heart rate to a safer level"),("Digoxin","Controls the heart rate in AF"),("Amiodarone","Restores normal heart rhythm")],
        "specs":[("Heart Doctor (Cardiologist)","Manages irregular heart rhythms"),("Electrophysiologist","Performs procedures to fix heart rhythm")],
        "tips":["Take blood thinners every day without fail","Limit alcohol — it triggers AF attacks","Monitor heart rate regularly","Avoid excess caffeine"],
    },
    "Anaemia": {
        "plain":"Low Blood / Anaemia", "icon":"🩸", "color":"#be123c",
        "category":"❤️ Heart & Blood", "icd10":"D64.9", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 2 weeks",
        "what":"Anaemia means too few red blood cells or not enough haemoglobin to carry oxygen. The body doesn't get enough oxygen making you feel tired and weak.",
        "aliases":["anaemia","anemia","iron deficiency","low haemoglobin","low hemoglobin","iron deficiency anaemia"],
        "kws":["anaemia","anemia","haemoglobin","hemoglobin","iron deficiency","pallor","fatigue","ferritin","low hb","hematocrit","microcytic","macrocytic","thalassemia"],
        "boost":["anaemia","haemoglobin","iron deficiency","pallor","ferritin"],
        "symptoms":["Extreme tiredness and weakness","Looking pale — pale skin, lips, inner eyelids","Breathlessness with little effort","Dizziness or feeling faint"],
        "meds":[("Ferrous Sulphate","Iron tablet — take with orange juice"),("Folic Acid","B vitamin needed to make red blood cells"),("Vitamin B12 injection","For B12 deficiency anaemia — given monthly"),("Erythropoietin","Injection to stimulate red blood cell production")],
        "specs":[("Blood Doctor (Haematologist)","Specialist for blood disorders"),("General Physician","Can investigate and treat common anaemias")],
        "tips":["Eat iron-rich food — red meat, spinach, lentils","Eat vitamin C with iron-rich foods","Avoid tea and coffee with meals — they block iron","Cook in iron pans if possible"],
    },
    "Deep Vein Thrombosis (DVT)": {
        "plain":"Blood Clot in Leg (DVT)", "icon":"🦵", "color":"#9f1239",
        "category":"❤️ Heart & Blood", "icd10":"I82.409", "urgency_level":"high",
        "urgency":"⚠️ See a doctor urgently — clot can travel to lungs",
        "what":"A blood clot forms in a deep vein, usually in the leg. The danger is that the clot can break off and travel to the lungs (pulmonary embolism) which is life-threatening.",
        "aliases":["dvt","deep vein thrombosis","blood clot leg","venous thrombosis","thrombosis"],
        "kws":["dvt","deep vein thrombosis","thrombosis","calf pain","leg swelling","leg pain","swollen leg","clot","anticoagulant","heparin","compression","d-dimer","doppler"],
        "boost":["dvt","thrombosis","calf pain","leg swelling","d-dimer"],
        "symptoms":["Swollen red warm leg — usually one side only","Calf pain or tenderness","Skin feels warm to touch in affected area","Sometimes no symptoms at all"],
        "meds":[("Heparin injection","Immediate blood thinner given in hospital"),("Rivaroxaban / Apixaban","Oral blood thinners taken at home for 3–6 months"),("Compression stockings","Reduces swelling and prevents recurrence")],
        "specs":[("Blood Doctor / Vascular Surgeon","Manages blood clot treatment")],
        "tips":["Keep moving — do not stay still for long periods","Stay well hydrated","Wear compression stockings when travelling","Take blood thinners exactly as prescribed"],
    },

    # ══════════════════════════════════════════════════════
    # BRAIN & NERVES
    # ══════════════════════════════════════════════════════
    "Stroke": {
        "plain":"Brain Attack (Stroke)", "icon":"🧠", "color":"#7c3aed",
        "category":"🧠 Brain & Nerves", "icd10":"I63.9", "urgency_level":"critical",
        "urgency":"🚨 CALL EMERGENCY SERVICES IMMEDIATELY — every second counts",
        "what":"A stroke happens when blood supply to part of the brain is blocked or a blood vessel bursts. Brain cells die very quickly. Remember FAST: Face drooping, Arm weakness, Speech problems, Time to call emergency.",
        "aliases":["stroke","cerebrovascular accident","cva","tia","brain attack","ischemic stroke","hemorrhagic stroke","transient ischemic attack"],
        "kws":["stroke","cva","facial droop","weakness","aphasia","slurred speech","hemiplegia","hemianopia","infarction","tia","cerebrovascular","mri brain","ct brain","facial drooping"],
        "boost":["stroke","facial droop","weakness","aphasia","hemiplegia","cva"],
        "symptoms":["Sudden face drooping on one side","Sudden arm or leg weakness on one side","Sudden difficulty speaking or understanding","Sudden severe headache with no cause"],
        "meds":[("Alteplase (tPA)","Clot-busting injection — must be given within 4.5 hours in hospital"),("Aspirin","Prevents further clots after stroke"),("Clopidogrel","Blood thinner used after stroke"),("Atorvastatin","Reduces cholesterol to prevent another stroke")],
        "specs":[("Brain Doctor (Neurologist)","Specialist for stroke diagnosis"),("Stroke Rehabilitation Team","Physiotherapist, speech therapist, occupational therapist for recovery")],
        "tips":["Learn FAST — Face, Arms, Speech, Time — call emergency immediately","Control blood pressure and diabetes","Complete all rehabilitation exercises every day","Take all prescribed medicines without fail"],
    },
    "Migraine": {
        "plain":"Severe Headache Attack (Migraine)", "icon":"🤕", "color":"#6d28d9",
        "category":"🧠 Brain & Nerves", "icd10":"G43.909", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 6 weeks",
        "what":"Migraines are intense headaches usually on one side that can last hours or days. Often triggered by bright lights, stress, certain foods or hormonal changes.",
        "aliases":["migraine","migraine headache","hemiplegic migraine","classical migraine","common migraine"],
        "kws":["migraine","headache","photophobia","aura","throbbing","nausea","vomiting","phonophobia","unilateral","visual disturbance","scintillating","scotoma"],
        "boost":["migraine","photophobia","aura","throbbing","unilateral headache"],
        "symptoms":["Throbbing pain on one side of head","Sensitive to light and loud sounds","Feeling sick and sometimes vomiting","Seeing zigzag lines or flashing lights before headache"],
        "meds":[("Sumatriptan","Take at the very first sign of migraine"),("Ibuprofen","Common painkiller from any pharmacy"),("Topiramate","Daily tablet to prevent migraines"),("Amitriptyline","Nightly tablet reducing frequency of attacks")],
        "specs":[("Brain & Nerve Doctor (Neurologist)","Specialist for headaches"),("Headache Clinic","Specialist clinics for chronic migraine")],
        "tips":["Keep a diary to identify your personal triggers","Sleep regular hours","Stay hydrated and never skip meals","Rest in a dark quiet room during an attack"],
    },
    "Epilepsy": {
        "plain":"Epilepsy (Seizures / Fits)", "icon":"⚡", "color":"#8b5cf6",
        "category":"🧠 Brain & Nerves", "icd10":"G40.909", "urgency_level":"high",
        "urgency":"⚠️ See a neurologist within 2 weeks",
        "what":"Epilepsy causes repeated seizures due to sudden bursts of abnormal electrical activity in the brain. Seizures can vary from brief blank staring to full body convulsions.",
        "aliases":["epilepsy","seizure","fits","convulsion","tonic clonic","absence seizure","grand mal"],
        "kws":["epilepsy","seizure","convulsion","fit","eeg","anticonvulsant","tonic","clonic","postictal","levetiracetam","sodium valproate","absence","grand mal"],
        "boost":["epilepsy","seizure","convulsion","fit","tonic clonic"],
        "symptoms":["Sudden uncontrolled shaking of body","Brief periods of blank staring","Temporary confusion after the episode","Sometimes loss of bladder control during attack"],
        "meds":[("Levetiracetam","Most common anti-seizure tablet — taken twice daily"),("Sodium Valproate","Effective anti-seizure medicine"),("Lamotrigine","Well-tolerated seizure medicine"),("Carbamazepine","Effective for certain types of epilepsy")],
        "specs":[("Brain & Nerve Doctor (Neurologist)","Diagnoses and manages epilepsy"),("Epilepsy Specialist Nurse","Ongoing support and medication advice")],
        "tips":["Never stop seizure medicine without doctor advice","Never swim or bathe alone","Inform your employer and driving authority","Wear a medical alert bracelet"],
    },
    "Parkinson's Disease": {
        "plain":"Parkinson's Disease (Shaking Illness)", "icon":"🤲", "color":"#4f46e5",
        "category":"🧠 Brain & Nerves", "icd10":"G20", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4 weeks",
        "what":"Parkinson's is where brain cells that produce dopamine slowly die. Without dopamine the brain cannot control movement properly, causing tremors, stiffness and slow movement.",
        "aliases":["parkinson","parkinsons disease","parkinsonism","resting tremor"],
        "kws":["parkinson","tremor","rigidity","bradykinesia","dopamine","levodopa","shuffling gait","masked face","pill rolling","resting tremor","cogwheel"],
        "boost":["parkinson","tremor","rigidity","bradykinesia","levodopa"],
        "symptoms":["Shaking of hands or limbs even at rest","Moving very slowly","Stiff muscles and reduced arm swing when walking","Soft quiet voice and reduced facial expression"],
        "meds":[("Levodopa / Carbidopa","Most effective Parkinson's medicine — replaces missing dopamine"),("Pramipexole","Dopamine-like medicine used in early Parkinson's"),("Rasagiline","Slows breakdown of dopamine"),("Amantadine","Reduces involuntary movements")],
        "specs":[("Brain & Nerve Doctor (Neurologist)","Manages Parkinson's treatment"),("Movement Disorder Specialist","Specifically treats Parkinson's and tremor")],
        "tips":["Physiotherapy helps maintain movement — start early","Speech therapy helps with soft voice","Eat high-fibre diet — constipation is very common in Parkinson's","Exercise every day — proven to slow progression"],
    },
    "Alzheimer's Disease": {
        "plain":"Alzheimer's (Memory Loss Disease)", "icon":"🔵", "color":"#1d4ed8",
        "category":"🧠 Brain & Nerves", "icd10":"G30.9", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4 weeks",
        "what":"Alzheimer's is the most common form of dementia. Brain cells gradually die causing progressive memory loss, confusion and difficulty with daily tasks.",
        "aliases":["alzheimer","alzheimers","dementia","memory loss","cognitive decline","vascular dementia"],
        "kws":["alzheimer","dementia","memory loss","confusion","forgetfulness","cognitive","mmse","moca","behavioural change","wandering","sundowning","cognitive impairment"],
        "boost":["alzheimer","dementia","memory loss","confusion","cognitive"],
        "symptoms":["Forgetting recent events repeatedly","Getting confused about time and place","Struggling to find the right words","Changes in personality and behaviour"],
        "meds":[("Donepezil","Helps improve memory and thinking — does not cure but helps"),("Rivastigmine","Slows memory decline"),("Memantine","Used in moderate to severe stages"),("Vitamin E","Antioxidant supplement sometimes recommended")],
        "specs":[("Brain & Nerve Doctor (Neurologist)","Diagnoses and manages Alzheimer's"),("Geriatrician","Specialist for elderly patients")],
        "tips":["Keep mentally active — puzzles, reading and socialising help","Maintain regular daily routines to reduce confusion","Ensure home safety — remove trip hazards","Join a carer support group"],
    },

    # ══════════════════════════════════════════════════════
    # STOMACH & DIGESTION
    # ══════════════════════════════════════════════════════
    "Gastroesophageal Reflux Disease (GERD)": {
        "plain":"Acid Reflux (Heartburn Disease)", "icon":"🔥", "color":"#d97706",
        "category":"🍽️ Stomach & Digestion", "icd10":"K21.0", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4–6 weeks",
        "what":"Stomach acid flows back up into the food pipe causing burning in the chest. A valve between the stomach and food pipe is not closing properly.",
        "aliases":["gerd","gastroesophageal reflux","acid reflux","gord","heartburn disease"],
        "kws":["heartburn","acid reflux","regurgitation","esophagus","burning","epigastric","gerd","gord","dyspepsia","waterbrash","ppi","acid","reflux"],
        "boost":["heartburn","reflux","regurgitation","epigastric","acid"],
        "symptoms":["Burning in chest after eating","Sour or acid taste in the mouth","Food or acid coming back up","Worse when lying down at night"],
        "meds":[("Omeprazole","Tablet before meals — reduces acid your stomach makes"),("Ranitidine","Blocks acid production for several hours"),("Antacids (Tums/Gaviscon)","Immediate heartburn relief"),("Lansoprazole","Similar to Omeprazole")],
        "specs":[("Stomach Doctor (Gastroenterologist)","Specialist for stomach, food pipe and digestion")],
        "tips":["Eat smaller meals","Don't lie down for 2 hours after eating","Avoid spicy food, coffee and alcohol","Elevate head of bed by 4–6 inches"],
    },
    "Peptic Ulcer": {
        "plain":"Stomach Ulcer (Peptic Ulcer)", "icon":"🫙", "color":"#b45309",
        "category":"🍽️ Stomach & Digestion", "icd10":"K27.9", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 1 week",
        "what":"A painful sore develops in the lining of the stomach or first part of the small intestine. Usually caused by H. pylori bacteria or taking too many anti-inflammatory painkillers.",
        "aliases":["peptic ulcer","stomach ulcer","gastric ulcer","duodenal ulcer","h pylori infection"],
        "kws":["ulcer","peptic","gastric","h pylori","helicobacter","epigastric pain","melena","hematemesis","endoscopy","gnawing pain","night pain","omeprazole","duodenal"],
        "boost":["ulcer","peptic","h pylori","epigastric pain","melena","hematemesis"],
        "symptoms":["Burning or gnawing pain in stomach area","Pain comes and goes — often worse when hungry","Pain that wakes you at night","Nausea, loss of appetite or vomiting"],
        "meds":[("Omeprazole / Lansoprazole","Reduces acid allowing ulcer to heal"),("Amoxicillin + Clarithromycin","Antibiotics to kill H. pylori bacteria"),("Antacids","Immediate short-term pain relief"),("Sucralfate","Coats the ulcer surface to protect it")],
        "specs":[("Stomach Doctor (Gastroenterologist)","Diagnoses and treats stomach ulcers"),("Endoscopy Team","Camera test to see and treat the ulcer")],
        "tips":["Avoid anti-inflammatory painkillers (ibuprofen, aspirin)","Eat smaller more frequent meals","Avoid alcohol and smoking","Complete the full antibiotic course if H. pylori is found"],
    },
    "Irritable Bowel Syndrome (IBS)": {
        "plain":"IBS (Irritable Bowel / Sensitive Gut)", "icon":"🫠", "color":"#ca8a04",
        "category":"🍽️ Stomach & Digestion", "icd10":"K58.9", "urgency_level":"low",
        "urgency":"📅 See a doctor within 6 weeks",
        "what":"IBS is a common condition where the bowel is very sensitive and works abnormally. It causes cramping, bloating, diarrhoea and constipation — often triggered by stress or certain foods.",
        "aliases":["ibs","irritable bowel","irritable colon","spastic colon","functional bowel disorder"],
        "kws":["ibs","irritable bowel","bloating","cramping","diarrhoea","constipation","abdominal pain","mucus stool","altered bowel habit","bowel habit"],
        "boost":["ibs","irritable bowel","bloating","cramping"],
        "symptoms":["Cramping stomach pain relieved by going to toilet","Bloating and feeling full","Switching between diarrhoea and constipation","Passing mucus from the back passage"],
        "meds":[("Mebeverine","Relaxes cramping bowel muscle"),("Loperamide (Imodium)","For diarrhoea-type IBS"),("Laxatives (Lactulose)","For constipation-type IBS"),("Peppermint oil capsules","Natural — reduces bloating and cramps")],
        "specs":[("Stomach Doctor (Gastroenterologist)","Diagnoses IBS and rules out serious conditions"),("Dietitian","Advises on low-FODMAP diet")],
        "tips":["Try the low-FODMAP diet","Exercise regularly — improves gut movement","Manage stress — gut and brain are closely linked","Keep a food and symptom diary"],
    },
    "Appendicitis": {
        "plain":"Appendix Infection (Appendicitis)", "icon":"🔴", "color":"#ef4444",
        "category":"🍽️ Stomach & Digestion", "icd10":"K37", "urgency_level":"critical",
        "urgency":"🚨 Go to hospital immediately — may need emergency surgery",
        "what":"When the appendix gets blocked and infected it causes severe pain. If untreated it can burst and become life-threatening.",
        "aliases":["appendicitis","appendix pain","appendix inflammation","appendix infection"],
        "kws":["appendicitis","mcburney","rebound tenderness","peritonitis","right iliac fossa","rif pain","rovsing","nausea","fever","appendix","guarding"],
        "boost":["appendicitis","rebound tenderness","right iliac fossa","peritonitis"],
        "symptoms":["Pain that starts around belly button then moves to lower right","Pain gets steadily worse over hours","Nausea and vomiting","Fever and loss of appetite"],
        "meds":[("Antibiotics","Given before and after surgery to prevent infection"),("IV Pain Relief","Morphine or similar given in hospital"),("Surgery (Appendectomy)","Removal of the appendix — usually keyhole surgery")],
        "specs":[("Emergency Surgeon","Performs appendix removal surgery"),("Emergency Medicine Doctor","First assessment and management")],
        "tips":["Do not delay — go to hospital immediately","Complete full antibiotic course after surgery","Eat light diet initially after surgery"],
    },
    "Liver Cirrhosis": {
        "plain":"Liver Scarring (Cirrhosis)", "icon":"🫧", "color":"#92400e",
        "category":"🍽️ Stomach & Digestion", "icd10":"K74.60", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 1 week",
        "what":"Cirrhosis is scarring of the liver caused by long-term damage from alcohol, hepatitis or fatty liver. The scar tissue stops the liver working properly.",
        "aliases":["cirrhosis","liver cirrhosis","liver failure","hepatic cirrhosis","liver disease","hepatitis"],
        "kws":["cirrhosis","jaundice","ascites","varices","encephalopathy","portal hypertension","liver failure","splenomegaly","albumin","bilirubin","liver biopsy","hepatitis"],
        "boost":["cirrhosis","jaundice","ascites","varices","encephalopathy"],
        "symptoms":["Yellow skin and eyes (jaundice)","Swollen belly filled with fluid","Extreme tiredness and weakness","Easy bruising and bleeding"],
        "meds":[("Spironolactone / Furosemide","Removes fluid from swollen belly"),("Propranolol","Reduces pressure in veins to prevent bleeding"),("Lactulose","Prevents liver toxins from affecting the brain"),("Rifaximin","Antibiotic reducing brain complications")],
        "specs":[("Liver Doctor (Hepatologist)","Specialist for all liver conditions"),("Gastroenterologist","Manages complications of liver disease")],
        "tips":["Stop alcohol completely — absolutely essential","Eat small frequent high-protein meals","Avoid ibuprofen and paracetamol overdose","Regular blood tests and scans to monitor progression"],
    },

    # ══════════════════════════════════════════════════════
    # DIABETES & HORMONES
    # ══════════════════════════════════════════════════════
    "Type 2 Diabetes Mellitus": {
        "plain":"Type 2 Diabetes (High Blood Sugar)", "icon":"🩸", "color":"#db2777",
        "category":"🩸 Diabetes & Hormones", "icd10":"E11.9", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 3 months",
        "what":"The body does not make enough insulin or does not use it properly. Sugar builds up in blood instead of providing energy. Long-term high sugar damages nerves, kidneys, eyes and heart.",
        "aliases":["type 2 diabetes","diabetes mellitus","t2dm","type 2 diabetes mellitus","sugar disease","diabetes"],
        "kws":["diabetes","glucose","hba1c","metformin","insulin","hyperglycemia","polyuria","polydipsia","type 2","blood sugar","fasting glucose","glucometer","diabetic"],
        "boost":["diabetes","glucose","hba1c","hyperglycemia","polyuria","diabetic"],
        "symptoms":["Feeling very thirsty all the time","Needing to urinate very frequently","Feeling tired even after rest","Slow healing of cuts and wounds"],
        "meds":[("Metformin","First tablet for diabetes — helps body use sugar better"),("Insulin","Injection that directly lowers blood sugar"),("Sitagliptin","Helps release the right insulin after meals"),("Empagliflozin","Removes excess sugar through urine")],
        "specs":[("Diabetes Doctor (Endocrinologist)","Manages diabetes and blood sugar"),("Diabetes Educator","Teaches practical daily management")],
        "tips":["Eat less sugar, white rice, bread and processed foods","Exercise 30 minutes daily","Check blood sugar regularly","Attend all diabetes review appointments"],
    },
    "Type 1 Diabetes": {
        "plain":"Type 1 Diabetes (Insulin-Dependent)", "icon":"💉", "color":"#be185d",
        "category":"🩸 Diabetes & Hormones", "icd10":"E10.9", "urgency_level":"high",
        "urgency":"⚠️ Requires lifelong insulin — see a doctor regularly",
        "what":"The immune system attacks and destroys the cells that make insulin. The body cannot make any insulin at all. Insulin injections are needed every day for life.",
        "aliases":["type 1 diabetes","insulin dependent diabetes","juvenile diabetes","t1dm","autoimmune diabetes"],
        "kws":["type 1 diabetes","insulin","ketoacidosis","dka","autoimmune","islet","hypoglycemia","hypoglycaemia","blood glucose","hba1c","pump","continuous glucose monitor","t1dm"],
        "boost":["type 1 diabetes","insulin","ketoacidosis","hypoglycemia","dka"],
        "symptoms":["Extreme thirst and frequent urination","Rapid unexplained weight loss","Feeling very tired","Blurred vision and sweet-smelling breath in severe cases"],
        "meds":[("Basal Insulin (Glargine/Detemir)","Long-acting insulin — once daily background"),("Bolus Insulin (Novorapid)","Fast-acting insulin given before every meal"),("Glucose tablets or juice","Corrects dangerously low blood sugar immediately"),("Glucagon injection","Emergency injection for severe hypoglycaemia")],
        "specs":[("Diabetes Doctor (Endocrinologist)","Specialist for Type 1 diabetes management"),("Diabetes Dietitian","Teaches carbohydrate counting for insulin doses")],
        "tips":["Never miss an insulin dose — even when unwell","Always carry glucose for hypoglycaemia emergencies","Wear a medical alert bracelet","Check blood sugar before driving and before sleep"],
    },
    "Diabetic Neuropathy": {
        "plain":"Nerve Damage from Diabetes", "icon":"⚡", "color":"#9333ea",
        "category":"🩸 Diabetes & Hormones", "icd10":"E11.40", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 3 months",
        "what":"Long-term high blood sugar slowly damages tiny nerves — especially in feet and hands — causing tingling, numbness and burning pain.",
        "aliases":["diabetic neuropathy","peripheral neuropathy","diabetic nerve damage","neuropathy"],
        "kws":["neuropathy","numbness","tingling","burning feet","diabetic foot","peripheral","monofilament","vibration sense","ankle reflex","nerve damage","burning pain"],
        "boost":["neuropathy","numbness","tingling","burning feet","peripheral"],
        "symptoms":["Tingling or pins-and-needles in feet or hands","Numbness — cannot feel hot or cold","Burning or stabbing pain especially at night","Feet very sensitive even to light touch"],
        "meds":[("Pregabalin","Specifically for nerve pain — reduces tingling and burning"),("Gabapentin","Calms overactive nerve signals"),("Amitriptyline","Very effective for nerve pain at night"),("Duloxetine","Treats nerve pain and helps mood")],
        "specs":[("Diabetes Doctor (Endocrinologist)","Manages diabetes causing nerve damage"),("Nerve Specialist (Neurologist)","Treats nerve damage directly")],
        "tips":["Check feet every single day for cuts, blisters or sores","Keep blood sugar tightly controlled","Wear comfortable well-fitting shoes","Report any foot wound to doctor immediately"],
    },
    "Hypothyroidism": {
        "plain":"Underactive Thyroid (Slow Thyroid)", "icon":"🦋", "color":"#0e7490",
        "category":"🩸 Diabetes & Hormones", "icd10":"E03.9", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4 weeks",
        "what":"The thyroid gland produces too little thyroid hormone. This slows down all body functions — making you feel tired, cold, and causing weight gain.",
        "aliases":["hypothyroidism","underactive thyroid","low thyroid","hashimoto","hashimoto thyroiditis"],
        "kws":["hypothyroidism","thyroid","tsh","t4","thyroxine","levothyroxine","goitre","fatigue","weight gain","cold intolerance","bradycardia","hashimoto","underactive"],
        "boost":["hypothyroidism","thyroid","tsh","thyroxine","levothyroxine","hashimoto"],
        "symptoms":["Extreme tiredness that rest does not fix","Weight gain without eating more","Feeling cold all the time","Dry skin, hair loss and slow heart rate"],
        "meds":[("Levothyroxine","Daily tablet on empty stomach — replaces missing thyroid hormone"),("TSH blood tests every 6–12 weeks","Until dose is correct")],
        "specs":[("Hormone Doctor (Endocrinologist)","Manages thyroid conditions"),("General Physician","Can prescribe and monitor levothyroxine")],
        "tips":["Take levothyroxine on empty stomach 30 minutes before breakfast","Never stop or change dose without doctor advice","Get TSH blood test every 6–12 months","Avoid soya and calcium supplements near the time of tablet"],
    },
    "Hyperthyroidism": {
        "plain":"Overactive Thyroid (Fast Thyroid)", "icon":"⚡", "color":"#0891b2",
        "category":"🩸 Diabetes & Hormones", "icd10":"E05.90", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 2 weeks",
        "what":"The thyroid gland produces too much hormone, speeding up all body functions. This causes a racing heart, weight loss and anxiety. Left untreated it can cause dangerous heart problems.",
        "aliases":["hyperthyroidism","overactive thyroid","graves disease","thyrotoxicosis","graves"],
        "kws":["hyperthyroidism","thyrotoxicosis","graves","tsh low","t4 high","exophthalmos","goitre","tremor","palpitations","heat intolerance","weight loss","overactive thyroid"],
        "boost":["hyperthyroidism","thyrotoxicosis","tsh low","graves","exophthalmos"],
        "symptoms":["Racing heartbeat even at rest","Unexplained weight loss despite eating normally","Feeling very hot and sweating","Nervousness, trembling hands and difficulty sleeping"],
        "meds":[("Carbimazole","Blocks thyroid from making too much hormone"),("Propylthiouracil","Alternative to carbimazole"),("Propranolol","Controls fast heart rate"),("Radioiodine","One-off treatment that reduces thyroid activity permanently")],
        "specs":[("Hormone Doctor (Endocrinologist)","Specialist for thyroid conditions"),("Ophthalmologist","If eyes are affected by Graves' disease")],
        "tips":["Take medication at the same time every day","Avoid excess iodine (seaweed, iodine supplements)","Protect eyes from UV light if affected","Regular blood tests to monitor thyroid levels"],
    },

    # ══════════════════════════════════════════════════════
    # BONES & JOINTS
    # ══════════════════════════════════════════════════════
    "Osteoarthritis": {
        "plain":"Joint Wear and Tear (Osteoarthritis)", "icon":"🦴", "color":"#0891b2",
        "category":"🦴 Bones & Joints", "icd10":"M19.90", "urgency_level":"low",
        "urgency":"📅 See a doctor within 6 weeks",
        "what":"Osteoarthritis is wear and tear of the cartilage cushioning joints. Without cushioning, bone rubs on bone causing pain, stiffness and reduced movement.",
        "aliases":["osteoarthritis","oa","joint pain","wear and tear","knee arthritis","hip arthritis","degenerative joint"],
        "kws":["osteoarthritis","arthritis","joint pain","stiffness","crepitus","osteophytes","joint space narrowing","knee pain","hip pain","morning stiffness","bone on bone"],
        "boost":["osteoarthritis","arthritis","joint pain","stiffness","crepitus"],
        "symptoms":["Joint pain that gets worse with activity","Stiffness in the morning that eases within 30 minutes","Joints that crack or crunch when moving","Swelling around affected joints"],
        "meds":[("Paracetamol","First-line pain tablet — take regularly"),("Ibuprofen gel","Anti-inflammatory gel rubbed onto painful joint"),("Naproxen","Anti-inflammatory tablet for more severe pain"),("Glucosamine","Supplement that may help some people")],
        "specs":[("Joint Doctor (Rheumatologist)","Specialist for arthritis"),("Orthopaedic Surgeon","Performs joint replacement surgery when needed")],
        "tips":["Regular gentle exercise — swimming and cycling are ideal","Lose weight if overweight — small loss massively reduces knee pain","Use a walking stick if needed","Hot or cold packs on painful joints provide relief"],
    },
    "Rheumatoid Arthritis": {
        "plain":"Rheumatoid Arthritis (Immune Joint Attack)", "icon":"🤝", "color":"#0e7490",
        "category":"🦴 Bones & Joints", "icd10":"M06.9", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 2 weeks — early treatment prevents joint damage",
        "what":"Rheumatoid arthritis is an autoimmune disease where the immune system attacks the joints. Unlike osteoarthritis it affects many joints at the same time and causes significant inflammation.",
        "aliases":["rheumatoid arthritis","ra","inflammatory arthritis","autoimmune arthritis","rheumatoid"],
        "kws":["rheumatoid","arthritis","synovitis","morning stiffness","rheumatoid factor","anti ccp","joints","swelling","methotrexate","inflammation","symmetrical","small joints"],
        "boost":["rheumatoid","synovitis","morning stiffness","rheumatoid factor","anti ccp"],
        "symptoms":["Painful swollen joints — typically small joints of hands and feet","Morning stiffness lasting more than 1 hour","Both sides of the body affected equally","Fatigue and feeling generally unwell"],
        "meds":[("Methotrexate","Main disease-modifying drug — slows immune attack on joints"),("Hydroxychloroquine","Anti-malarial drug also effective for mild RA"),("Prednisolone","Steroid tablet — rapid relief during flare-ups"),("Adalimumab (Humira)","Biologic injection for severe RA")],
        "specs":[("Joint Specialist (Rheumatologist)","Specialist for all inflammatory arthritis")],
        "tips":["Take disease-modifying medicines every week without fail","Joint protection techniques — use larger joints for tasks","Physiotherapy for strength and joint protection","Rest during flare-ups"],
    },
    "Osteoporosis": {
        "plain":"Weak Bones (Osteoporosis)", "icon":"🦷", "color":"#155e75",
        "category":"🦴 Bones & Joints", "icd10":"M81.0", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 4 weeks",
        "what":"Osteoporosis means bones become fragile and break easily. It develops silently with no symptoms until a bone breaks — often from a minor fall.",
        "aliases":["osteoporosis","osteopenia","brittle bones","low bone density","fragility fracture"],
        "kws":["osteoporosis","fracture","dexa","bone density","t score","bisphosphonate","calcium","vitamin d","fragility","vertebral fracture","spine","alendronate"],
        "boost":["osteoporosis","fracture","bone density","bisphosphonate","dexa"],
        "symptoms":["Often no symptoms until a bone breaks","Back pain from a collapsed spinal bone","Gradually becoming shorter in height","Bones breaking easily from small falls"],
        "meds":[("Alendronate","Weekly tablet strengthening bones"),("Calcium supplements","Builds and maintains bone strength"),("Vitamin D supplement","Needed for calcium absorption into bones"),("Denosumab","6-monthly injection preventing bone breakdown")],
        "specs":[("Bone Specialist (Rheumatologist / Endocrinologist)","Manages osteoporosis treatment"),("Physiotherapist","Teaches balance and strengthening exercises")],
        "tips":["Take calcium and vitamin D supplement every day","Weight-bearing exercise (walking, dancing) strengthens bones","Remove trip hazards at home — most fractures happen from falls","Do not smoke — smoking accelerates bone loss"],
    },
    "Gout": {
        "plain":"Gout (Uric Acid Joint Attack)", "icon":"🦶", "color":"#1d4ed8",
        "category":"🦴 Bones & Joints", "icd10":"M10.9", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 1 week",
        "what":"Gout is caused by too much uric acid in the blood. Crystals form in joints — usually the big toe — causing sudden agonising pain, redness and swelling.",
        "aliases":["gout","hyperuricemia","uric acid","gouty arthritis","tophus","podagra"],
        "kws":["gout","uric acid","hyperuricemia","tophi","big toe","podagra","colchicine","allopurinol","red hot joint","acute gout","serum urate"],
        "boost":["gout","uric acid","tophi","big toe","podagra","hyperuricemia"],
        "symptoms":["Sudden severe pain in big toe — often at night","Affected joint is hot, red and very swollen","Even light touch is unbearable during attack","Attack usually improves within a week"],
        "meds":[("Colchicine","Taken immediately when attack starts — reduces inflammation quickly"),("Ibuprofen / Naproxen","Anti-inflammatory tablets for pain"),("Allopurinol","Daily tablet to reduce uric acid"),("Prednisolone","Short steroid course for severe attacks")],
        "specs":[("Joint Specialist (Rheumatologist)","Manages recurrent gout"),("General Physician","Can treat and prevent most gout cases")],
        "tips":["Drink at least 2 litres of water daily — most important prevention","Reduce alcohol especially beer and spirits","Avoid red meat, shellfish and organ meat","Lose weight gradually"],
    },

    # ══════════════════════════════════════════════════════
    # KIDNEYS & UROLOGY
    # ══════════════════════════════════════════════════════
    "Chronic Kidney Disease": {
        "plain":"Kidney Damage (Chronic Kidney Disease)", "icon":"🫘", "color":"#059669",
        "category":"🫘 Kidneys & Urology", "icd10":"N18.9", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 2 weeks",
        "what":"The kidneys are slowly losing their ability to filter waste from the blood. CKD develops over years and is often caused by diabetes or high blood pressure.",
        "aliases":["chronic kidney disease","ckd","kidney failure","renal failure","nephropathy","renal impairment"],
        "kws":["kidney","renal","creatinine","gfr","egfr","proteinuria","kidney failure","ckd","dialysis","nephropathy","urea","potassium","oliguria","renal impairment"],
        "boost":["kidney","renal","creatinine","egfr","kidney failure","dialysis"],
        "symptoms":["Swollen ankles and around eyes in morning","Feeling very tired and short of breath","Passing very little or very dark urine","Nausea, poor appetite and itchy skin"],
        "meds":[("Ramipril / Lisinopril","Protects kidneys and slows damage progression"),("Furosemide","Water tablet to remove extra fluid"),("Erythropoietin injection","Treats anaemia caused by kidney disease"),("Phosphate binders","Prevents high phosphate levels harming bones")],
        "specs":[("Kidney Doctor (Nephrologist)","Specialist for kidney disease and dialysis")],
        "tips":["Control blood pressure and diabetes tightly","Avoid ibuprofen and anti-inflammatory painkillers","Keep all kidney monitoring appointments","Eat low-potassium, low-salt diet as advised"],
    },
    "Urinary Tract Infection (UTI)": {
        "plain":"Urine Infection (UTI)", "icon":"💧", "color":"#0891b2",
        "category":"🫘 Kidneys & Urology", "icd10":"N39.0", "urgency_level":"low",
        "urgency":"📅 Get treated within 1 week",
        "what":"Bacteria have entered the urinary system causing infection. Very common especially in women. Usually clears up quickly with antibiotics.",
        "aliases":["uti","urinary tract infection","cystitis","bladder infection","urine infection"],
        "kws":["uti","dysuria","urinary frequency","urgency","burning urine","cystitis","cloudy urine","nitrites","leukocytes","bladder","urine culture"],
        "boost":["dysuria","frequency","urgency","bladder","burning urine","uti"],
        "symptoms":["Burning or stinging when urinating","Needing to urinate urgently and very frequently","Cloudy or bad-smelling urine","Pain or pressure in lower belly"],
        "meds":[("Trimethoprim","Simple antibiotic taken 7 days — clears most UTIs"),("Nitrofurantoin","Antibiotic concentrated in urine — very effective"),("Ciprofloxacin","Stronger antibiotic if simpler ones don't work")],
        "specs":[("Kidney & Bladder Doctor (Urologist)","For recurrent or complicated UTIs"),("General Physician","Can treat most straightforward UTIs")],
        "tips":["Drink plenty of water daily","Urinate as soon as you feel the urge","Wipe front to back after toilet","Urinate after sexual activity"],
    },
    "Kidney Stones": {
        "plain":"Kidney Stones", "icon":"🪨", "color":"#047857",
        "category":"🫘 Kidneys & Urology", "icd10":"N20.0", "urgency_level":"high",
        "urgency":"⚠️ Go to A&E if pain is very severe",
        "what":"Hard crystals form inside the kidneys from minerals in urine. Small stones can pass naturally causing severe pain. Larger stones may need treatment to break them up.",
        "aliases":["kidney stones","renal calculi","urolithiasis","nephrolithiasis","renal stone","ureteric stone"],
        "kws":["kidney stone","renal calculus","colic","haematuria","flank pain","ureteric stone","lithotripsy","calculi","blood urine","loin pain","renal colic"],
        "boost":["kidney stone","renal calculus","colic","haematuria","flank pain"],
        "symptoms":["Sudden severe pain in side and back — comes in waves","Pain that travels down to groin","Blood in urine (pink or brown)","Nausea and vomiting with the pain"],
        "meds":[("Diclofenac / Ibuprofen","Strong pain relief during stone passage"),("Tamsulosin","Relaxes ureter muscles to help stone pass"),("IV Morphine","Powerful pain relief in hospital"),("Lithotripsy","Shock wave treatment to break up large stones")],
        "specs":[("Kidney & Bladder Doctor (Urologist)","Manages and treats kidney stones")],
        "tips":["Drink 2–3 litres of water every day — most important prevention","Reduce salt and animal protein","Collect urine in a strainer to retrieve stone for analysis","Get regular imaging if recurrent"],
    },

    # ══════════════════════════════════════════════════════
    # MENTAL HEALTH
    # ══════════════════════════════════════════════════════
    "Anxiety Disorder": {
        "plain":"Anxiety & Worry Disorder", "icon":"🧘", "color":"#6d28d9",
        "category":"🧠 Mental Health", "icd10":"F41.1", "urgency_level":"medium",
        "urgency":"📅 See a doctor within 2–4 weeks",
        "what":"Anxiety disorder means feeling excessively worried, nervous or scared — far more than normal and often without a clear reason. Physical symptoms like racing heart and breathlessness are common.",
        "aliases":["anxiety","generalised anxiety","gad","anxiety disorder","panic disorder","panic attacks"],
        "kws":["anxiety","worry","panic","panic attack","nervousness","palpitations","restlessness","gad","generalised anxiety","agoraphobia","social anxiety","phobia"],
        "boost":["anxiety","panic","worry","nervousness","panic attack"],
        "symptoms":["Feeling worried or scared most of the time","Racing heartbeat or chest tightness","Difficulty sleeping due to racing thoughts","Feeling restless and unable to relax"],
        "meds":[("Sertraline","Antidepressant very effective for anxiety — takes 4–6 weeks"),("Lorazepam","Short-term relief for severe panic attacks only"),("Buspirone","Non-addictive daily anxiety medicine"),("Escitalopram","Well-tolerated medicine for generalised anxiety")],
        "specs":[("Mental Health Doctor (Psychiatrist)","Prescribes medication for anxiety"),("Therapist / Counsellor","CBT talking therapy as effective as tablets")],
        "tips":["Deep breathing exercises every day genuinely help","Regular exercise is one of the most effective anxiety treatments","Limit caffeine and alcohol","Talk to someone you trust"],
    },
    "Depression": {
        "plain":"Depression (Low Mood Illness)", "icon":"🌧️", "color":"#4338ca",
        "category":"🧠 Mental Health", "icd10":"F32.9", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 1–2 weeks — do not suffer alone",
        "what":"Depression is a medical condition where chemicals in the brain are out of balance, causing persistent low mood, loss of interest, and sometimes thoughts of suicide. It is very treatable.",
        "aliases":["depression","major depression","depressive disorder","low mood","mdd","clinical depression"],
        "kws":["depression","low mood","anhedonia","suicidal","hopeless","worthless","insomnia","hypersomnia","fatigue","antidepressant","ssri","psychotherapy","depressed"],
        "boost":["depression","low mood","anhedonia","suicidal","hopeless","depressed"],
        "symptoms":["Feeling very low, empty or hopeless most days","Losing interest in things you used to enjoy","Sleeping too much or too little","Feeling worthless or thinking about death or suicide"],
        "meds":[("Sertraline","Most commonly prescribed antidepressant — takes 4–6 weeks"),("Fluoxetine (Prozac)","Well-known antidepressant for depression"),("Mirtazapine","Also helps sleep — useful when depression causes severe insomnia"),("Venlafaxine","For moderate to severe depression")],
        "specs":[("Mental Health Doctor (Psychiatrist)","Prescribes medication for depression"),("Psychologist / Therapist","CBT therapy as effective as medication for many")],
        "tips":["Tell someone how you feel — do not suffer in silence","Gentle exercise daily releases chemicals that improve mood","Maintain social contact even when you don't want to","If you have thoughts of harming yourself call a crisis line immediately"],
    },
    "Schizophrenia": {
        "plain":"Schizophrenia (Mind Perception Disorder)", "icon":"🌀", "color":"#5b21b6",
        "category":"🧠 Mental Health", "icd10":"F20.9", "urgency_level":"high",
        "urgency":"⚠️ See a psychiatrist urgently",
        "what":"Schizophrenia is a serious mental health condition where the brain misinterprets reality. People may hear voices, see things that aren't there, or have false beliefs. Manageable with medication.",
        "aliases":["schizophrenia","psychosis","hallucinations","delusions","schizoaffective","psychotic disorder"],
        "kws":["schizophrenia","psychosis","hallucinations","delusions","voices","paranoia","antipsychotic","risperidone","olanzapine","clozapine","disorganised","thought disorder"],
        "boost":["schizophrenia","psychosis","hallucinations","delusions","paranoia"],
        "symptoms":["Hearing voices or seeing things others don't","Strong fixed beliefs that seem very unusual","Disorganised thinking and speech","Becoming very withdrawn and avoiding people"],
        "meds":[("Risperidone","Antipsychotic reducing hallucinations and delusions"),("Olanzapine","Effective antipsychotic for positive and negative symptoms"),("Clozapine","Most effective for treatment-resistant cases"),("Long-acting injection","Monthly or 3-monthly injection for those who forget tablets")],
        "specs":[("Mental Health Doctor (Psychiatrist)","Essential for schizophrenia management"),("Community Mental Health Team","Provides ongoing daily life support")],
        "tips":["Take medication every day — stopping causes relapse","Establish a regular daily routine","Avoid cannabis and recreational drugs — they worsen psychosis","Learn to recognise your early warning signs"],
    },
    "Bipolar Disorder": {
        "plain":"Bipolar Disorder (Extreme Mood Swings)", "icon":"🔄", "color":"#7e22ce",
        "category":"🧠 Mental Health", "icd10":"F31.9", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 1–2 weeks",
        "what":"Bipolar disorder causes extreme shifts in mood — from very high energetic states (mania) to very low depressive states. Episodes can last days to months.",
        "aliases":["bipolar","bipolar disorder","manic depression","mania","hypomania","bipolar affective"],
        "kws":["bipolar","mania","hypomania","manic","depression","mood swings","lithium","grandiosity","reduced sleep","hypersexuality","flight of ideas","elation"],
        "boost":["bipolar","mania","hypomania","manic","mood swings"],
        "symptoms":["Periods of very high energy — feeling you don't need sleep","Spending money recklessly and making impulsive decisions","Alternating with periods of very low mood","Rapid or jumbled speech during manic episodes"],
        "meds":[("Lithium","Most effective mood stabiliser — prevents both highs and lows"),("Valproate","Mood stabiliser particularly good for preventing mania"),("Quetiapine","Antipsychotic used as mood stabiliser in bipolar"),("Lamotrigine","Effective at preventing depressive episodes")],
        "specs":[("Mental Health Doctor (Psychiatrist)","Essential for bipolar diagnosis and management")],
        "tips":["Take mood stabilisers every day without fail","Maintain a very regular sleep schedule","Keep a mood diary to spot early warning signs","Have a crisis plan agreed with your doctor"],
    },

    # ══════════════════════════════════════════════════════
    # INFECTIONS
    # ══════════════════════════════════════════════════════
    "COVID-19": {
        "plain":"COVID-19 (Coronavirus Infection)", "icon":"🦠", "color":"#dc2626",
        "category":"🦠 Infections", "icd10":"U07.1", "urgency_level":"medium",
        "urgency":"⚠️ Isolate immediately and consult a doctor if breathless",
        "what":"COVID-19 is an infectious illness caused by the SARS-CoV-2 coronavirus. Symptoms range from mild cold-like illness to severe pneumonia.",
        "aliases":["covid","covid-19","coronavirus","sars-cov-2","covid pneumonia","post-covid"],
        "kws":["covid","coronavirus","sars","fever","cough","anosmia","loss of smell","loss of taste","dyspnea","oxygen saturation","isolation","pcr","rapid antigen","covid-19"],
        "boost":["covid","coronavirus","anosmia","loss of smell","pcr"],
        "symptoms":["Fever and persistent cough","Loss of smell or taste","Shortness of breath","Fatigue and muscle aches"],
        "meds":[("Paracetamol","For fever and pain relief"),("Paxlovid","Antiviral for high-risk patients — start within 5 days"),("Remdesivir","Antiviral given in hospital for severe cases"),("Dexamethasone","Steroid given in hospital when oxygen is needed")],
        "specs":[("Infectious Disease Specialist","For severe or complicated COVID"),("Respiratory Physician","If lungs are significantly affected")],
        "tips":["Isolate immediately to protect others","Monitor oxygen levels — below 94% needs hospital","Rest and drink plenty of fluids","Seek emergency care if breathless at rest"],
    },
    "Dengue Fever": {
        "plain":"Dengue Fever (Mosquito Fever)", "icon":"🦟", "color":"#b45309",
        "category":"🦠 Infections", "icd10":"A97.9", "urgency_level":"high",
        "urgency":"⚠️ See a doctor within 24 hours",
        "what":"Dengue is a viral infection spread by Aedes mosquito bites. It causes very high fever, severe headache and muscle pain. Severe dengue can cause dangerous bleeding.",
        "aliases":["dengue","dengue fever","dengue hemorrhagic fever","breakbone fever","dengue viral"],
        "kws":["dengue","dengue fever","platelet","thrombocytopenia","hemorrhage","rash","retroorbital","myalgia","arthralgia","aedes","mosquito","ns1","dengue igm"],
        "boost":["dengue","platelet","retroorbital","ns1","thrombocytopenia"],
        "symptoms":["Very high sudden fever (40°C / 104°F)","Severe headache behind the eyes","Severe muscle and joint pain","Skin rash appearing 3–4 days into illness"],
        "meds":[("Paracetamol","For fever and pain — do NOT use ibuprofen"),("IV Fluids","In hospital to prevent dangerous drop in blood pressure"),("Platelet transfusion","Only if platelet count drops dangerously low")],
        "specs":[("Infectious Disease Specialist","Manages dengue and monitors for complications")],
        "tips":["Drink 2–3 litres of oral rehydration fluid every day","Monitor for warning signs: vomiting blood, black stool","Avoid ibuprofen, aspirin and steroids","Prevent mosquito bites — use repellent and nets"],
    },
    "Malaria": {
        "plain":"Malaria (Mosquito Parasite Fever)", "icon":"🌿", "color":"#166534",
        "category":"🦠 Infections", "icd10":"B54", "urgency_level":"high",
        "urgency":"🚨 See a doctor immediately — malaria can be fatal",
        "what":"Malaria is caused by a parasite transmitted through mosquito bites. It causes recurring bouts of fever, chills and sweating. Falciparum malaria can affect the brain and organs.",
        "aliases":["malaria","plasmodium","falciparum malaria","vivax malaria","cerebral malaria","malaria fever"],
        "kws":["malaria","plasmodium","falciparum","vivax","fever","chills","rigors","blood smear","rdt","artemisinin","chloroquine","splenomegaly","cerebral malaria","malarial"],
        "boost":["malaria","plasmodium","falciparum","blood smear","rigors"],
        "symptoms":["Cyclical high fever with shaking chills","Profuse sweating when fever breaks","Headache, muscle ache and fatigue","Feeling very ill — nausea, vomiting, jaundice"],
        "meds":[("Artemether-Lumefantrine (Coartem)","First-line treatment for falciparum malaria"),("Chloroquine","Used for non-falciparum malaria"),("IV Artesunate","Hospital injection for severe malaria"),("Primaquine","Clears liver-stage vivax malaria")],
        "specs":[("Infectious Disease Specialist","Manages malaria treatment and monitoring")],
        "tips":["Complete the full course of antimalarial tablets","Seek medical care immediately if fever returns","Use mosquito nets and insect repellent","Preventive malaria tablets if travelling to high-risk areas"],
    },
    "Typhoid Fever": {
        "plain":"Typhoid (Contaminated Water Fever)", "icon":"💧", "color":"#92400e",
        "category":"🦠 Infections", "icd10":"A01.00", "urgency_level":"high",
        "urgency":"⚠️ See a doctor immediately",
        "what":"Typhoid is a bacterial infection spread through contaminated food and water. It causes prolonged high fever, abdominal pain and in severe cases can cause life-threatening intestinal perforation.",
        "aliases":["typhoid","typhoid fever","enteric fever","salmonella typhi","typhoid salmonella"],
        "kws":["typhoid","enteric fever","salmonella","fever","rash","rose spots","constipation","diarrhoea","widal","blood culture","ceftriaxone","step ladder fever"],
        "boost":["typhoid","enteric fever","salmonella","widal","rose spots"],
        "symptoms":["Prolonged high fever that rises in steps over days","Abdominal pain and constipation in early stages","Headache and feeling very weak","Pink spots appearing on the trunk"],
        "meds":[("Ceftriaxone","Injection antibiotic — most effective in hospital"),("Ciprofloxacin","Antibiotic tablet for uncomplicated typhoid"),("Azithromycin","Used where antibiotic resistance is common")],
        "specs":[("Infectious Disease Specialist","Manages typhoid and severe complications")],
        "tips":["Drink only clean safe water — boil or use purification tablets","Eat only freshly cooked hot food","Typhoid vaccine available before travel to high-risk areas","Complete full antibiotic course"],
    },

    # ══════════════════════════════════════════════════════
    # SKIN & EYES
    # ══════════════════════════════════════════════════════
    "Eczema": {
        "plain":"Eczema (Itchy Inflamed Skin)", "icon":"🤲", "color":"#0f766e",
        "category":"👁️ Skin & Eyes", "icd10":"L20.9", "urgency_level":"low",
        "urgency":"📅 See a doctor within 6 weeks",
        "what":"Eczema is a condition where the skin becomes inflamed, red and very itchy. The skin barrier doesn't work properly letting moisture out and irritants in.",
        "aliases":["eczema","atopic dermatitis","atopic eczema","dermatitis","contact dermatitis"],
        "kws":["eczema","dermatitis","pruritus","itching","atopic","emollient","steroid cream","moisturiser","flare","rash","excoriation","scratch"],
        "boost":["eczema","dermatitis","pruritus","itching","atopic"],
        "symptoms":["Intensely itchy skin — often worst at night","Red, dry, scaly patches of skin","Skin that becomes thick from scratching","Weeping or crusting skin during flare-ups"],
        "meds":[("Emollient moisturisers","Apply after every wash — most important treatment"),("Hydrocortisone cream","For mild flares — apply to red areas"),("Betamethasone cream","For severe or persistent flares"),("Antihistamine tablets","Reduces itching especially at night")],
        "specs":[("Skin Doctor (Dermatologist)","For severe or uncontrolled eczema")],
        "tips":["Moisturise at least twice a day — every day not just in flares","Use mild unscented soap — avoid bubble baths","Wear cotton clothing — avoid wool and synthetic fabrics","Keep fingernails short to reduce skin damage from scratching"],
    },
    "Psoriasis": {
        "plain":"Psoriasis (Scaly Skin Condition)", "icon":"🩹", "color":"#0d9488",
        "category":"👁️ Skin & Eyes", "icd10":"L40.0", "urgency_level":"low",
        "urgency":"📅 See a doctor within 6 weeks",
        "what":"Psoriasis is a skin condition where skin cells multiply much too fast causing thick, red, scaly patches. It is not infectious and can also affect joints.",
        "aliases":["psoriasis","plaque psoriasis","psoriatic arthritis","silvery scales","scalp psoriasis"],
        "kws":["psoriasis","plaques","silvery scales","scalp psoriasis","psoriatic arthritis","phototherapy","methotrexate","biologic","koebner","plaque","silvery"],
        "boost":["psoriasis","plaques","silvery scales","psoriatic"],
        "symptoms":["Raised red patches covered with thick silvery-white scales","Itching and burning on affected areas","Dry skin that cracks and bleeds","Nail pitting and thickening"],
        "meds":[("Coal tar preparations","Traditional effective treatment reducing scaling"),("Betamethasone + Calcipotriol cream","Most effective combination for psoriasis"),("Methotrexate","Weekly tablet for moderate-severe psoriasis"),("Adalimumab (Humira)","Biologic injection for severe psoriasis")],
        "specs":[("Skin Doctor (Dermatologist)","Specialist for psoriasis treatment")],
        "tips":["Moisturise daily — keeps skin comfortable and reduces scaling","Avoid skin trauma — wounds can trigger psoriasis","Reduce alcohol and stress — both are strong triggers","Sunshine in moderation helps most people"],
    },
    "Glaucoma": {
        "plain":"Glaucoma (Silent Sight Stealer)", "icon":"👁️", "color":"#0e7490",
        "category":"👁️ Skin & Eyes", "icd10":"H40.9", "urgency_level":"medium",
        "urgency":"⚠️ See an eye doctor within 2 weeks",
        "what":"Glaucoma damages the optic nerve — the nerve connecting eye to brain — causing gradual painless loss of peripheral (side) vision. Often caused by raised eye pressure.",
        "aliases":["glaucoma","raised intraocular pressure","iop","optic nerve damage","visual field loss","open angle glaucoma"],
        "kws":["glaucoma","intraocular pressure","optic nerve","visual field","iop","cup disc ratio","tonometry","trabeculoplasty","latanoprost","timolol","optic disc"],
        "boost":["glaucoma","intraocular pressure","optic nerve","visual field"],
        "symptoms":["Gradual loss of side vision — often unnoticed until advanced","Blurred vision or halos around lights","Eye pain and redness in acute attacks","Nausea in acute angle-closure glaucoma"],
        "meds":[("Latanoprost eye drops","Once-daily drops at night — lowers eye pressure"),("Timolol eye drops","Twice-daily drops reducing fluid production in eye"),("Dorzolamide drops","Reduces eye pressure by different mechanism"),("Laser treatment","Non-invasive procedure improving fluid drainage")],
        "specs":[("Eye Doctor (Ophthalmologist)","Specialist for glaucoma diagnosis and management")],
        "tips":["Use eye drops every day at the same time — never skip doses","Attend eye checks every 6–12 months","Inform family members — glaucoma runs in families","Regular exercise may help lower eye pressure"],
    },
    "Cataracts": {
        "plain":"Cataracts (Cloudy Eye Lens)", "icon":"🔍", "color":"#155e75",
        "category":"👁️ Skin & Eyes", "icd10":"H26.9", "urgency_level":"low",
        "urgency":"📅 See an eye doctor within 8 weeks",
        "what":"A cataract is when the clear lens inside the eye becomes cloudy and yellow — like looking through frosted glass. Very common with ageing. Simple surgery restores vision.",
        "aliases":["cataract","cloudy lens","cataract surgery","lens opacity","nuclear cataract"],
        "kws":["cataract","lens opacity","cloudy vision","visual acuity","phacoemulsification","intraocular lens","nuclear sclerosis","glare","halos","vision blurred gradually"],
        "boost":["cataract","cloudy vision","lens opacity","phacoemulsification"],
        "symptoms":["Vision becoming progressively blurry or hazy","Colours appearing faded or yellowed","Increased glare from headlights and sunlight","Needing brighter light to read"],
        "meds":[("Cataract surgery","Day case surgery under local anaesthetic — removes cloudy lens and replaces with clear artificial one"),("Updated glasses","Temporary — may help in early stages")],
        "specs":[("Eye Doctor / Surgeon (Ophthalmologist)","Performs cataract surgery")],
        "tips":["Wear sunglasses with UV protection outdoors","Good lighting for reading","Surgery is very safe — most people see clearly within days","Do not rub or touch the eye after surgery"],
    },

    # ── NEW SKIN DISEASES ──────────────────────────────────
    "Contact Dermatitis": {
        "plain":"Skin Allergy / Contact Dermatitis", "icon":"🤲", "color":"#0f766e",
        "category":"👁️ Skin & Eyes", "icd10":"L23.9", "urgency_level":"low",
        "urgency":"📅 See a doctor within 1 week if not improving",
        "what":"Contact dermatitis is a skin reaction caused by direct contact with an irritant or allergen — such as cosmetics, soaps, metals, detergents or plants. The skin becomes red, itchy and inflamed exactly where the substance touched it.",
        "aliases":["contact dermatitis","allergic contact dermatitis","irritant contact dermatitis",
                   "cosmetic allergy","cosmetic reaction","skin allergy","allergic dermatitis",
                   "contact rash","skin contact reaction"],
        "kws":["rash","itchy","erythema","erythematous","contact","cosmetic","irritation",
               "dermatitis","inflamed","inflammation","skin reaction","red patches","swelling",
               "pruritus","allergy","allergic","patch","skin","rashes","red rash","itching",
               "erythematous patches","cosmetic product","new product","allergic skin"],
        "boost":["rash","itchy","erythematous","cosmetic","dermatitis","erythema","pruritus",
                 "contact","inflamed","skin reaction","cosmetic product","red rash","allergic",
                 "rashes","itching","swelling"],
        "symptoms":["Red itchy rash exactly where the product/substance touched skin",
                    "Swelling, burning or stinging sensation on affected area",
                    "Dry scaly or cracked skin patches",
                    "Blisters that may weep or crust in severe cases"],
        "meds":[
            ("Hydrocortisone cream 1%","Mild steroid cream — apply twice daily to reduce redness and itching"),
            ("Cetirizine 10mg (antihistamine)","Once-daily tablet to stop allergic itching and reduce the reaction"),
            ("Calamine lotion","Apply directly to itchy skin — immediate soothing and cooling relief"),
            ("Betamethasone cream","Stronger steroid cream prescribed by doctor if rash does not improve in 5–7 days"),
        ],
        "specs":[
            ("Skin Doctor (Dermatologist)","Specialist for skin conditions — can do patch testing to find the exact allergen"),
            ("Allergy Specialist","Identifies the exact ingredient in the cosmetic causing the reaction"),
        ],
        "tips":["Stop using the new cosmetic product immediately — this is the most important step",
                "Wash the affected area with cool water and mild unscented soap",
                "Apply a cool damp cloth to reduce swelling and itching",
                "Do not scratch — scratching breaks skin and risks infection",
                "Wear loose cotton clothing — avoid wool and synthetic fabrics on affected area",
                "Keep the area cool — heat and sweat worsen contact dermatitis"],
    },

    "Allergic Reaction (Urticaria / Hives)": {
        "plain":"Skin Allergic Reaction (Hives / Urticaria)", "icon":"🌸", "color":"#be185d",
        "category":"👁️ Skin & Eyes", "icd10":"L50.0", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 24–48 hours if rash is spreading or not settling",
        "what":"Urticaria (hives) are raised itchy red welts that appear on the skin due to an allergic trigger such as cosmetics, food, medicine or insect bites. They usually resolve within hours to days once the trigger is removed.",
        "aliases":["urticaria","hives","allergic reaction","skin allergy","allergic rash",
                   "allergic hives","allergic skin reaction","wheals","welts","rash allergy"],
        "kws":["rash","hives","urticaria","itchy","swelling","allergic","allergy",
               "erythematous","red patches","cosmetic","irritation","skin","inflamed",
               "pruritus","erythema","wheals","welts","raised rash","itching","rashes",
               "red rash","allergic rash","new product","skin reaction"],
        "boost":["rash","hives","urticaria","itchy","swelling","allergic","cosmetic",
                 "erythematous","erythema","pruritus","red rash","raised rash","wheals"],
        "symptoms":["Raised red itchy welts on skin — may vary in size and shape",
                    "Swelling of the affected area — often appears quickly",
                    "Rash appeared after contact with a new product or substance",
                    "Itching that tends to get worse in the evening"],
        "meds":[
            ("Cetirizine (Zyrtec) 10mg","Antihistamine — take once daily to stop allergic itching and rash"),
            ("Loratadine (Claritin) 10mg","Non-drowsy antihistamine — take once daily"),
            ("Prednisolone (short 5-day course)","Steroid tablets if rash is severe or rapidly spreading — doctor prescribed"),
            ("Calamine lotion","Apply directly to itchy areas for soothing relief"),
        ],
        "specs":[
            ("Skin Doctor (Dermatologist)","Specialist for hives and allergic skin conditions"),
            ("Allergy Specialist","Identifies allergens causing repeated skin reactions"),
        ],
        "tips":["Identify and remove the trigger immediately — stop the new cosmetic",
                "Wear loose cotton clothing to avoid skin friction",
                "Keep affected area cool — heat worsens urticaria",
                "Do not scratch — scratching spreads histamine and makes it worse",
                "If lips, tongue or throat swell — this is an emergency, call ambulance immediately"],
    },

    "Acne Vulgaris": {
        "plain":"Acne (Pimples and Spots)", "icon":"😣", "color":"#c2410c",
        "category":"👁️ Skin & Eyes", "icd10":"L70.0", "urgency_level":"low",
        "urgency":"📅 See a doctor within 6–8 weeks if not improving",
        "what":"Acne is a very common skin condition where hair follicles become blocked with oil and dead skin cells. This causes spots, blackheads and whiteheads — mostly on the face, chest and back.",
        "aliases":["acne","pimples","spots","acne vulgaris","comedones","blackheads","whiteheads","zits"],
        "kws":["acne","pimples","spots","blackheads","whiteheads","comedones","sebum",
               "follicle","face spots","oily skin","nodules","pustules","papules","cysts",
               "inflammatory acne","hormonal acne","breakout","blemishes"],
        "boost":["acne","pimples","spots","blackheads","comedones","pustules","papules"],
        "symptoms":["Whiteheads and blackheads on face, chest or back",
                    "Red pus-filled spots (pustules)",
                    "Painful deep cysts under the skin",
                    "Oily skin with frequent breakouts"],
        "meds":[
            ("Benzoyl peroxide gel","Kills acne bacteria — apply to spots once daily"),
            ("Adapalene gel (Differin)","Retinoid cream that unblocks pores — apply at night"),
            ("Doxycycline (antibiotic)","Oral antibiotic for moderate acne — taken for 3 months"),
            ("Isotretinoin (Roaccutane)","Most powerful acne treatment — doctor prescribed for severe cases"),
        ],
        "specs":[
            ("Skin Doctor (Dermatologist)","Specialist for moderate to severe acne"),
            ("General Physician","Can prescribe initial treatments for mild to moderate acne"),
        ],
        "tips":["Wash face twice daily with a gentle cleanser — never over-wash",
                "Do not squeeze or pop spots — causes scarring and spreads bacteria",
                "Use non-comedogenic (oil-free) moisturisers and makeup",
                "Change pillowcase every 2–3 days"],
    },

    "Chickenpox (Varicella)": {
        "plain":"Chickenpox (Varicella Virus)", "icon":"🟡", "color":"#ca8a04",
        "category":"🦠 Infections", "icd10":"B01.9", "urgency_level":"medium",
        "urgency":"⚠️ See a doctor within 24 hours — highly contagious, isolate immediately",
        "what":"Chickenpox is a highly contagious viral infection causing an itchy blistering rash all over the body, fever and tiredness. Caused by the varicella-zoster virus. Very common in children but can be severe in adults.",
        "aliases":["chickenpox","varicella","chicken pox","varicella zoster","blistering rash"],
        "kws":["chickenpox","varicella","blisters","vesicles","itchy rash","fever","spots",
               "blister","crusting","rash","viral rash","contagious rash","pox"],
        "boost":["chickenpox","varicella","blisters","vesicles","viral rash","pox"],
        "symptoms":["Itchy fluid-filled blisters appearing in crops all over the body",
                    "Fever before and during the rash",
                    "Feeling tired and unwell",
                    "Blisters that crust over after 5–7 days"],
        "meds":[
            ("Calamine lotion","Apply to blisters — reduces itching"),
            ("Chlorphenamine (antihistamine)","Helps reduce itching especially at night"),
            ("Paracetamol","For fever and discomfort — do NOT use ibuprofen in chickenpox"),
            ("Aciclovir","Antiviral prescribed for severe cases or adults"),
        ],
        "specs":[
            ("General Physician","Manages most chickenpox cases"),
            ("Infectious Disease Specialist","For severe or complicated cases in adults"),
        ],
        "tips":["Isolate immediately — highly contagious for 5–7 days until blisters crust",
                "Do not scratch blisters — causes scarring and infection",
                "Keep fingernails short and clean",
                "Do not use ibuprofen — it increases risk of serious skin infection"],
    },

    "Fungal Skin Infection": {
        "plain":"Fungal Skin Infection (Ringworm / Tinea)", "icon":"🔵", "color":"#7c3aed",
        "category":"👁️ Skin & Eyes", "icd10":"B35.9", "urgency_level":"low",
        "urgency":"📅 See a doctor or pharmacist within 1–2 weeks",
        "what":"Fungal skin infections are caused by dermatophyte fungi living on the skin surface. Despite the name, ringworm has nothing to do with worms. It causes a ring-shaped scaly rash. Very common and easily treated with antifungal cream.",
        "aliases":["ringworm","tinea","fungal infection","athletes foot","jock itch","tinea corporis",
                   "tinea pedis","skin fungus","fungal rash"],
        "kws":["ringworm","tinea","fungal","athlete foot","jock itch","scaly rash","ring shaped",
               "circular rash","itchy ring","antifungal","clotrimazole","skin fungus","fungal skin"],
        "boost":["ringworm","tinea","fungal","circular rash","scaly rash","antifungal"],
        "symptoms":["Ring-shaped red scaly patch with clear centre",
                    "Itchy and slightly raised border of the ring",
                    "Gradually expanding circular rash",
                    "Athlete's foot: scaling and itching between the toes"],
        "meds":[
            ("Clotrimazole cream (Canesten)","Apply twice daily for 2–4 weeks — available without prescription"),
            ("Terbinafine cream","Very effective antifungal cream — apply once daily"),
            ("Terbinafine tablets","Oral antifungal for scalp ringworm or severe infections"),
            ("Ketoconazole shampoo","For scalp or facial fungal infections"),
        ],
        "specs":[
            ("Skin Doctor (Dermatologist)","For widespread or stubborn fungal infections"),
            ("General Physician / Pharmacist","Can diagnose and prescribe antifungal treatment"),
        ],
        "tips":["Keep affected area clean and dry — fungi thrive in moisture",
                "Do not share towels, clothes or combs",
                "Complete the full course of antifungal cream even after rash disappears",
                "Wear loose breathable cotton clothing"],
    },

    "Cellulitis": {
        "plain":"Skin Bacterial Infection (Cellulitis)", "icon":"🔴", "color":"#dc2626",
        "category":"👁️ Skin & Eyes", "icd10":"L03.90", "urgency_level":"high",
        "urgency":"⚠️ See a doctor urgently — cellulitis can spread rapidly",
        "what":"Cellulitis is a bacterial infection of the deeper layers of skin. It causes rapidly spreading redness, warmth, swelling and pain — usually on the legs or arms. It requires antibiotics promptly.",
        "aliases":["cellulitis","skin infection","bacterial skin infection","skin bacteria","erysipelas"],
        "kws":["cellulitis","skin infection","bacterial","erythema","swelling","warmth","redness",
               "spreading rash","hot skin","tender skin","fever","red spreading","bacterial infection",
               "skin bacteria","infected skin","spreading redness"],
        "boost":["cellulitis","skin infection","spreading rash","spreading redness","hot skin","warmth"],
        "symptoms":["Red, warm and swollen area of skin that is spreading",
                    "Skin feels hot and tender to touch",
                    "Fever and feeling generally unwell",
                    "Skin surface may look shiny and tight"],
        "meds":[
            ("Flucloxacillin (antibiotic)","First-choice antibiotic tablet for cellulitis — taken 4 times daily"),
            ("Co-amoxiclav","Alternative antibiotic if flucloxacillin cannot be used"),
            ("IV Benzylpenicillin","Hospital IV antibiotic for severe spreading cellulitis"),
            ("Paracetamol / Ibuprofen","For pain and fever relief"),
        ],
        "specs":[
            ("General Physician","Can diagnose and prescribe antibiotics for cellulitis"),
            ("Skin Doctor (Dermatologist)","For severe or recurrent cases"),
        ],
        "tips":["Start antibiotics as soon as prescribed — do not wait",
                "Draw around the red border with a pen to monitor if it is spreading",
                "Elevate the affected limb to reduce swelling",
                "Complete the full antibiotic course — usually 5–7 days"],
    },
}


def lookup_disease(name: str) -> tuple:
    """
    Returns (matched_key, info_dict) with fuzzy matching.
    Always returns something for any input.
    """
    if not name:
        return "", {}
    nl = name.lower().strip()
    # Exact match
    for k, v in DISEASE_DB.items():
        if k.lower() == nl:
            return k, v
    # Alias match
    for k, v in DISEASE_DB.items():
        for a in v.get("aliases", []):
            if a in nl or nl in a:
                return k, v
    # Partial key match
    for k, v in DISEASE_DB.items():
        base = k.lower().split("(")[0].strip()
        if nl in k.lower() or base in nl or any(w in k.lower() for w in nl.split() if len(w) > 4):
            return k, v
    return name, {}
